---

- name: Install packages
  apt: pkg={{ item }} state=present
  with_items:
    - curl
    - apt-transport-https
    - openssh-server
    - ca-certificates
  tags:
    - gitlab
    - packages

- name: Import GPG key
  apt_key: url=https://packages.gitlab.com/gpg.key
  tags:
    - gitlab
    - key

- name: Add source list
  apt_repository: repo='{{ item }} https://packages.gitlab.com/gitlab/gitlab-ce/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} main' state=present
  with_items:
    - deb
    - deb-src
  tags:
    - gitlab
    - source

- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - gitlab
    - cache

- name: Check installation
  stat: path=/etc/gitlab
  register: gitlab_config

- name: Stop existing server
  when: gitlab_config.stat.exists and gitlab_config.stat.isdir and upgrade_gitlab
  command: gitlab-ctl stop {{ item }}
  with_items:
    - unicorn
    - sidekiq
  tags:
    - gitlab
    - stop_server

- name: Backup database
  when: gitlab_config.stat.exists and gitlab_config.stat.isdir and upgrade_gitlab
  command: gitlab-rake gitlab:backup:create
  tags:
    - gitlab
    - backup

- name: Install GitLab CE
  apt: pkg=gitlab-ce state=latest
  tags:
    - gitlab
    - install

- name: Copy gitlab config
  template: src=gitlab.rb.j2 dest=/etc/gitlab/gitlab.rb
  tags:
    - gitlab
    - config

- name: Reconfigure
  command: gitlab-ctl reconfigure
  tags:
    - gitlab
    - reconfigure

- name: Restart all gitlab services
  command: gitlab-ctl restart
  tags:
    - gitlab
    - restart
