language: python
python: '2.7'
sudo: false
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - pip install ansible -q --download-cache $HOME/.pip-cache
script:
  - rake test_debian
notifications:
  email:
    recipients:
      - lexrus@gmail.com
    on_success: change
    on_failure: always