---
- hosts: all
  roles:
    - role: Ginsys.seafile
    - role: Ginsys.nginx
      post_tasks:
      - name:       allow web server access to seafile data
        user:
          name:     'www-data'
          groups:   '{{ seafile_user }}'
          append:   yes
