---
# A playbook for testing all roles.
- hosts: test
  sudo: yes

  roles:
    - role: common
    - role: nodejs
    - role: lesmyrmidons.mongodb
    - role: countly
    - role: gitlab
    - role: uptime
