---
# A playbook for testing all roles.
- hosts: test
  sudo: yes

  roles:
    - role: common
    - role: cow
    - role: cow/backend
    - role: cow/frontend
    - role: shadowsocks
    - role: nodejs
    - role: lesmyrmidons.mongodb
    - role: countly
