---

- name: Install nginx
  action: apt pkg=nginx state=installed
  tags:
    - gogs
    - nginx

- name: Add git user
  user: name=git home=/home/git state=present
  ignore_errors: yes
  tags:
    - gogs
    - user

- name: Remove existing gogs.zip
  raw: rm -rf /tmp/gogs{,.zip}
  tags:
    - gogs
    - remove

- name: Download Gogs binary {{ GOGS_VERSION }}
  get_url: >
    url=https://github.com/gogits/gogs/releases/download/v{{ GOGS_VERSION }}/linux_amd64.zip
    dest=/tmp/gogs.zip
    mode=0660
  tags:
    - gogs
    - download

- name: Unarchive Gogs
  unarchive: src=/tmp/gogs.zip dest=/tmp/ copy=no owner=git
  tags:
    - gogs
    - unarchive

- name: Stop existing Gogos
  supervisorctl: name=gogs state=stopped
  ignore_errors: yes
  tags:
    - gogs
    - stop

- name: Create directories
  file: path={{ item }} owner=git state=directory
  with_items:
    - /var/log/gogs
    - /home/git/gogs/custom/conf/
    - /home/git/.ssh
    - /home/git/gogs-repositories
  tags:
    - gogs
    - dir

- name: Remove backup
  raw: rm -rf /home/git/gogs-backup
  tags:
    - gogs
    - backup

- name: Backup existing Gogs
  raw: cp -R /home/git/gogs /home/git/gogs-backup
  tags:
    - gogs
    - backup

- name: Remove old templates
  raw: rm -rf /home/git/gogs/templates
  tags:
    - gogs
    - remove

- name: Upgrade to new Gogs
  raw: cp -a /tmp/gogs/. /home/git/gogs

- name: Touch authorized_keys
  file: path=/home/git/.ssh/authorized_keys owner=git state=touch mode=0600
  tags:
    - gogs
    - key

- name: Generate SECRET_KEY
  shell: mkpasswd
  register: SECRET_KEY
  tags:
    - gogs
    - config

- name: Copy Gogs config
  template: src=app.ini dest=/home/git/gogs/custom/conf/app.ini owner=git
  tags:
    - gogs
    - config

- name: Copy supervisor config
  template: src=gogs_supervisor.conf dest=/etc/supervisor/conf.d/gogs.conf
  notify:
    - "reload supervisor"
  tags:
    - gogs
    - supervisor

- name: Force stop gogs
  action: supervisorctl name=gogs state=stopped
  when: DISABLE_REGISTRATION == 'true'
  tags:
    - gogs
    - restart

- name: Wait for stop
  wait_for: timeout=2
  tags:
    - gogs
    - wait

- name: Force start gogs
  action: supervisorctl name=gogs state=started
  tags:
    - gogs
    - restart

- name: Test cert file
  command: find "/etc/nginx/ssl/{{ inventory_hostname }}/gogs.cer" -mmin +10080
  register: cert_file
  ignore_errors: true
  tags:
    - gogs
    - cert

- name: Include le_cert.yml
  include: le_cert.yml
  when: SSL and cert_file.stdout.find('gogs.cer') == -1
  tags:
    - gogs
    - cert

- name: Copy nginx config
  template: src=nginx-insecure.j2 dest=/etc/nginx/sites-available/gogs
  when: SSL == false
  tags:
    - gogs
    - nginx

- name: Enable nginx config
  file: src=/etc/nginx/sites-available/gogs dest=/etc/nginx/sites-enabled/gogs state=link
  when: SSL == false
  notify:
    - "reload nginx"
  tags:
    - gogs
    - nginx

- name: Set owner of all
  file: path={{ item }} owner=git recurse=yes
  with_items:
    - /home/git/gogs
    - /home/git/gogs-repositories
  tags:
    - gogs
    - owner
