---

- name: install curl
  apt: pkg=curl state=present
  tags:
    - nodejs
    - curl

- name: check node
  stat: path=/usr/bin/node
  register: node
  tags:
    - nodejs
    - check

- name: setup nodejs from nodesource
  raw: curl -sL https://deb.nodesource.com/setup | sudo bash -
  when: not node.stat.exists
  tags:
    - nodejs
    - nodesource

- name: install nodejs
  apt: pkg={{ item }} state=installed
  when: not node.stat.exists
  with_items:
    - nodejs
    - npm
  tags:
    - nodejs
    - install

- name: link nodejs to node
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link mode=755
  tags:
    - nodejs
    - link