---

# install & config ghost server

- name: create ghost folder
  file: path=/usr/local/ghost state=directory
  tags:
    - ghost
    - directory

- name: download ghost package
  get_url: url=https://ghost.org/zip/ghost-{{ ghost_version }}.zip dest=/tmp/
  tags:
    - ghost
    - download

- name: unzip ghost package
  unarchive: src=/tmp/ghost-{{ ghost_version }}.zip dest=/usr/local/ghost copy=no
  tags:
    - ghost
    - unarchive

- name: install node packages
  npm: path=/usr/local/ghost production=yes
  tags:
    - ghost
    - packages

- name: create default config
  template: src=config.js.j2 dest=/usr/local/ghost/config.js
  tags:
    - ghost
    - config

- name: add supervisor config
  template: src=ghost.conf.j2 dest=/etc/supervisor/conf.d/ghost.conf
  tags:
    - ghost
    - supervisor
  notify:
    - reload supervisor

- name: add nginx config
  template: src=nginx.j2 dest=/etc/nginx/sites-available/ghost.conf
  tags:
    - ghost
    - nginx_config

- name: enabled nginx config
  file: src=/etc/nginx/sites-available/ghost.conf dest=/etc/nginx/sites-enabled/ghost.conf state=link
  tags:
    - ghost
    - link_nginx_config
  notify:
    - reload nginx
