- name: reload supervisor
  shell: /etc/init.d/supervisor force-reload
  notify:
    - "restart gogs"
  tags:
    - gogs

- name: restart gogs
  action: supervisorctl name=gogs state=restarted
  tags:
    - gogs

- name: reload nginx
  service: name=nginx state=reloaded
  tags:
    - gogs
    - nginx
