---

- name: install nginx
  action: apt pkg=nginx state=installed
  tags:
    - countly
    - nginx

- name: install build-essential
  action: apt pkg=build-essential state=installed
  tags:
    - countly
    - build-essential

- name: clone countly
  git: repo=https://github.com/Countly/countly-server
       dest=/opt/countly
  tags:
    - countly
    - clone

- name: install time module for node
  npm: name=time path=/opt/countly/api production=yes state=present
  tags:
    - countly
    - time

- name: copy nginx config
  template: src=nginx.j2 dest=/etc/nginx/sites-available/countly
  tags:
    - countly
    - config_nginx

- name: enable nginx config
  file: src=/etc/nginx/sites-available/countly dest=/etc/nginx/sites-enabled/countly state=link
  notify:
    - "reload nginx"
  tags:
    - countly
    - symbol

- name: copy api config file
  command: cp /opt/countly/api/config.sample.js /opt/countly/api/config.js
  tags:
    - countly
    - config_api

- name: copy frontend config file
  command: cp /opt/countly/frontend/express/config.sample.js /opt/countly/frontend/express/config.js
  tags:
    - countly
    - config_frontend

- name: copy supervisor config
  template: src=supervisord.conf.j2 dest=/etc/supervisor/conf.d/countly.conf
  notify:
    - "reload supervisor"
  tags:
    - countly
    - supervisord_config
