---

- name: Prepare directories
  file: path={{ item }} state=directory mode=0700 group=www-data owner=www-data
  with_items:
    - /var/mediawiki/images
    - /var/mediawiki/mysql
    - /var/mediawiki/extensions
  tags:
    - mediawiki
    - dir

- name: Initiate MySQL container
  docker:
    name: mediawiki-mysql
    image: mysql
    state: started
    env:
      MYSQL_ROOT_PASSWORD: mediawiki
    volumes:
      - '/var/mediawiki/mysql:/var/lib/mysql:rw'
    expose:
      - 3306
  tags:
    - mediawiki
    - docker
    - mysql

- name: Initiate MediaWiki container
  docker:
    name: mediawiki
    image: simplyintricate/mediawiki
    state: present
    links:
      - 'mediawiki-mysql:db'
    ports:
      - 80:80
    volumes:
      - '/var/mediawiki/images:/usr/share/nginx/html/images'
      - '/var/mediawiki/extensions:/tmp/extensions'
  tags:
    - mediawiki
    - docker

- name: Upload LocalSettings.php
  copy: src=LocalSettings.php dest=/var/mediawiki/LocalSettings.php mode=0700 backup=yes group=www-data owner=www-data
  tags:
    - mediawiki
    - upload_settings

- name: Reload MediaWiki container
  docker:
    name: mediawiki
    image: simplyintricate/mediawiki
    state: reloaded
    links:
      - 'mediawiki-mysql:db'
    ports:
      - 80:80
    volumes:
      - '/var/mediawiki/LocalSettings.php:/usr/share/nginx/html/LocalSettings.php:ro'
      - '/var/mediawiki/images:/usr/share/nginx/html/images'
      - '/var/mediawiki/extensions:/tmp/extensions'
  tags:
    - mediawiki
    - docker
    - upload_settings
